relaychain:
  image: parity/polkadot:v1.1.0
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
  nodes:
    - name: alice
    - name: bob
    - name: charlie
